# This file has been autogenerated by the pywayland scanner

# Copyright 2015 Sean Vig
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

from .wl_core import WlCore  # noqa: F401
from .wl_destructor import WlDestructor  # noqa: F401
from .wl_events import WlEvents  # noqa: F401
from .wl_requests import WlRequests  # noqa: F401
from .wl_xfail import WlXfail  # noqa: F401
