# Copyright 2015 Sean Vig
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import contextlib
import re
import textwrap

from typing import List, Mapping, Match  # noqa: F401

head_msg = """\
# -*- coding: utf-8 -*-
# This file has been autogenerated by the pywayland scanner"""

# Match function calls wl_inter_face.function and interface names wl_interface
# while consuming any traling parentheses
re_doc = re.compile(r'(?P<iface>wl(?:_[a-z]+)+)(?P<func>\.[a-z]+(?:_[a-z]+)*)?(?:\(\))?')
# Match the start of lists
RE_DOC_LIST = re.compile(r'^(?P<list_head>\* |- )')
BASE_PATH = "pywayland.protocol"
DOC_WIDTH = 79
tab_stop = 4


class Printer(object):
    def __init__(self, protocol: str, interface_name: str = None, interface_imports: Mapping[str, str] = None) -> None:
        """Base level printer object

        Allows for storing of lines to be output from the definition of a
        protocol.  Lines are added by directly calling the printer object.

        :param protocol:
            The name of the protocol that is currently being generated, used
            for determining import resolution.
        :param interface_name:
            The name of the interface that is being generated, used for
            determining import resolution.
        :param interface_imports:
            The map from the interface name to the protocol it is defined in,
            for resolving imports.
        """
        self._level = 0
        self._lines = [
            head_msg, ''
        ]
        self._protocol_name = protocol
        self._interface_name = interface_name
        self._interface_imports = interface_imports

        self._re_interface_funcs = None
        self._re_interface_class = None
        if interface_imports is not None:
            interface_names = "|".join(sorted(interface_imports, key=len, reverse=True))
            self._re_interface_funcs = re.compile(r"(?P<interface>{})\.(?P<func>[a-z]+(?:_[a-z]+)*)(?:\(\))?".format(
                interface_names
            ))
            self._re_interface_class = re.compile(r"(?P<interface>{})".format(interface_names))

    def __call__(self, new_line: str = None) -> None:
        """Add the new line to the printer

        :param new_line:
            The new line to add to the file, should be appropriately wrapped.
        """
        if new_line:
            self._lines.append((' ' * tab_stop * self._level) + new_line)
        else:
            self._lines.append('')

    def docstring(self, docstring: str) -> None:
        """Add lines as docstrings

        In addition to the operations performed by :meth:`Printer.doc()`, will
        wrap text passed to it to the correct width.

        :param docstring:
            The docstring line to add to the printer.
        """
        docstring = self._parse_doc_line(docstring)

        # create a list of properly indented paragraphs
        paragraphs = []  # type: List[str]
        for paragraph in docstring.split('\n\n'):
            # try to detect and properly output lists
            doc_list_match = RE_DOC_LIST.search(paragraph.lstrip())

            base_width = DOC_WIDTH - tab_stop * self._level
            if doc_list_match is None:
                # not a list, just create the paragraph
                paragraphs.append(textwrap.fill(paragraph, width=base_width, break_long_words=False))
            else:
                # the list items are not always separated by paragraph breaks,
                # so parse each line and see if they denote list items
                start_list = doc_list_match.group("list_head")
                lines = paragraph.split("\n")
                current_list_item = [lines[0].strip()]
                list_items = []  # type: List[str]
                for line in lines[1:]:
                    if line.strip().startswith(start_list):
                        # store the current list item
                        list_items.append(" ".join(current_list_item))
                        # start a new list item
                        current_list_item = [line.strip()]
                    else:
                        current_list_item.append(line.strip())
                # store the last list item
                list_items.append(" ".join(current_list_item))

                # add each list item as a new paragraph
                paragraphs.extend(
                    textwrap.fill(
                        list_item,
                        width=base_width,
                        subsequent_indent=" " * len(start_list),
                        break_long_words=False
                    ) for list_item in list_items
                )

        wrapped = '\n\n'.join(paragraphs)
        for line in wrapped.split('\n'):
            self(line)

    def doc(self, new_line: str) -> None:
        """Add lines as docstrings

        Performs additional massaging of strings, replacing references to other
        protocols and protocol methods with the appropriate Sphinx
        cross-reference.

        :param new_line:
            The new line to add to the printer output.
        """
        new_line = self._parse_doc_line(new_line)
        self(new_line)

    def _parse_doc_line(self, line):
        assert self._re_interface_funcs is not None
        assert self._re_interface_class is not None

        line = self._re_interface_funcs.sub(self._doc_funcs_replace, line)
        line = self._re_interface_class.sub(self._doc_class_replace, line)
        return line

    def _doc_class_replace(self, match: Match) -> str:
        """Build the sphinx doc class import

        :param match:
            The regex match for the given interface class.
        :returns:
            The string corresponding to the sphinx formatted class.
        """
        interface_name = match.group("interface")
        interface_class = "".join(x.capitalize() for x in interface_name.split("_"))

        if interface_name == self._interface_name:
            return ':class:`{}`'.format(interface_class)
        elif self._interface_imports is not None and interface_name in self._interface_imports:
            protocol_path = self._interface_imports[interface_name]
            return ':class:`~{base_path}.{iface}.{class_name}`'.format(
                class_name=interface_class,
                base_path=BASE_PATH,
                iface=protocol_path,
            )
        else:
            return '`{}`'.format(interface_class)

    def _doc_funcs_replace(self, match: Match):
        """Build the sphinx doc function definition

        :param match:
            The regex match for the given interface and function.
        :returns:
            The string corresponding to the sphinx formatted function.
        """
        interface_name = match.group("interface")
        function_name = match.group("func")
        interface_class = "".join(x.capitalize() for x in interface_name.split("_"))

        if interface_name == self._interface_name:
            return ':func:`{}.{}()`'.format(interface_class, function_name)
        elif self._interface_imports is not None and interface_name in self._interface_imports:
            protocol_path = self._interface_imports[interface_name]
            return ':func:`{class_name}.{func}() <{base_path}.{iface}.{class_name}.{func}>`'.format(
                class_name=interface_class,
                func=function_name,
                base_path=BASE_PATH,
                iface=protocol_path,
            )

    @contextlib.contextmanager
    def indented(self):
        """Indent in a level in the context manager block"""
        self._level += 1
        yield
        self._level -= 1

    def write(self, f) -> None:
        """Write the lines added to the printer out to the given file"""
        for line in self._lines:
            f.write(line.encode('utf-8'))
            f.write(b'\n')
